// swift-tools-version: 6.2
// Generated by tools/xcodeproj2xtool.py from FixtureApp.xcodeproj
// (target FixtureApp). Regenerate after changing the Xcode project.
import PackageDescription

let package = Package(
    name: "FixtureApp",
    defaultLocalization: "en",
    platforms: [.iOS("17.0")],
    products: [
    .library(name: "FixtureApp", targets: ["FixtureApp"]),
    ],
    dependencies: [
        .package(name: "DemoKit", path: "../proj/DemoPkg")
    ],
    targets: [
        .target(
            name: "FixtureApp",
            dependencies: [
                .product(name: "DemoKit", package: "DemoKit"),
            ],
            exclude: [
                "iOS/Info.plist",
            ],
            resources: [
                .process("iOS/Localizable.xcstrings"),
            ],
            swiftSettings: [.swiftLanguageMode(.v5), .enableUpcomingFeature("BareSlashRegexLiterals")]
        ),
    ]
)
