#!/usr/bin/env bash
# Build an App Store .ipa from the xtool project in the current directory,
# validate it offline, and optionally upload it to App Store Connect.
#
#   ship.sh            build, sign, validate (no Apple account needed: signs with
#                      a local TEST identity unless ASC_KEY_ID is set)
#   ship.sh --upload   the same with your Apple identity, then upload. Needs:
#                        ASC_KEY_PATH=/path/to/AuthKey_XXXXXXXXXX.p8
#                        ASC_ISSUER_ID=<issuer uuid>  ASC_KEY_ID=XXXXXXXXXX
#                      and the app record created once in App Store Connect.
#   ship.sh --device [TEAMID]
#                      build for a device install: steps 1-3, then every other
#                      resource of the app and its extensions copied to the
#                      bundle roots, as Xcode lays out an app. No signing,
#                      validation or upload; `xtool install xtool/<App>.app`
#                      signs and installs. With TEAMID, the team-prefix
#                      placeholders are filled first (tools/fill-team-prefix.py).
#
# BUILD_NUMBER sets CFBundleVersion (default: UTC yyyymmddHHMM, always increasing).
# XCODE_VERSION/XCODE_BUILD stamp DTXcode when the SDK came from a .xip.
set -euo pipefail

here=$(dirname "$(readlink -f "$0")")
PY="$HOME/pymobile3-venv/bin/python"
ASC="$here/tools/asc.py"
# SwiftPM keeps Swift SDKs under $XDG_CONFIG_HOME/swiftpm when that is set, else ~/.swiftpm.
darwin_sdk="${XDG_CONFIG_HOME:+$XDG_CONFIG_HOME/swiftpm}"
darwin_sdk="${darwin_sdk:-$HOME/.swiftpm}/swift-sdks/darwin.artifactbundle"
# ACTOOL overrides the actool binary (default: the SDK stand-in installed by
# install-toolchain.sh) — used to A/B a rebuilt Linux actool without
# reinstalling the toolchain.
ACTOOL="${ACTOOL:-$darwin_sdk/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/actool}"
# Icon settings generated by xcodeproj2xtool.py (APP_ICON, ALTERNATE_APP_ICONS,
# INCLUDE_ALL_APP_ICONS, STANDALONE_ICON_BEHAVIOR, EXTENSION_APP_ICONS).
# Environment values win over the file.
[ -f xtool.env ] && . ./xtool.env
PATH="$(dirname "$(readlink -f "$(command -v swift)")"):$HOME/.local/bin:$PATH"
export PATH

upload=0; device=0; team=
case "${1:-}" in
  --upload) upload=1 ;;
  --device) device=1; team=${2:-}
    [ $# -le 2 ] || { echo "usage: ship.sh --device [TEAMID]" >&2; exit 2; } ;;
  "") ;;
  *) echo "usage: ship.sh [--upload] | [--device [TEAMID]]" >&2; exit 2 ;;
esac
if [ "$upload" = 1 ]; then
  : "${ASC_KEY_ID:?--upload needs ASC_KEY_ID}" "${ASC_ISSUER_ID:?--upload needs ASC_ISSUER_ID}"
  : "${ASC_KEY_PATH:?--upload needs ASC_KEY_PATH (the .p8 file)}"
  export ASC_KEY_ID ASC_ISSUER_ID ASC_KEY_PATH
fi

stage=$(mktemp -d)
trap 'rm -rf "$stage"' EXIT
echo "== 1. Release build =="
xtool dev build --configuration release
app=$(find xtool -maxdepth 1 -name '*.app' -print -quit)
[ -n "$app" ] || { echo "no .app under xtool/" >&2; exit 1; }

echo "== 2. Interface Builder and extension file placement =="
# SwiftPM puts each target's resources in its resource bundle (<Package>_<Target>.bundle), but UIKit
# and App Store processing look for these at the root of the app or extension, where Xcode puts them:
# compiled storyboards and nibs (UIMainStoryboardFile, NSExtensionMainStoryboard: ITMS-90029/90357)
# and an action extension's NSExtensionJavaScriptPreprocessingFile (ITMS-90362). The rest stays in
# the bundle: code built by SwiftPM reads it through Bundle.module, and its Assets.car would collide
# with the app icon car at the root.
for target in "$app" "$app"/PlugIns/*.appex; do
  [ -d "$target" ] || continue
  name=$(basename "${target%.*}")
  resbundle=$(find "$target" -maxdepth 1 -type d -name "*_$name.bundle" -print -quit)
  [ -n "$resbundle" ] || continue
  js=$("$PY" -c 'import plistlib,sys; print(plistlib.load(open(sys.argv[1],"rb")).get("NSExtension",{}).get("NSExtensionAttributes",{}).get("NSExtensionJavaScriptPreprocessingFile",""))' "$target/Info.plist")
  while IFS= read -r -d '' rel; do
    rel=${rel#./}
    mkdir -p "$target/$(dirname "$rel")"
    mv "$resbundle/$rel" "$target/$rel"
  done < <(cd "$resbundle" && find . \( -name '*.storyboardc' -o -name '*.nib' ${js:+-o -name "$js.js"} \) -prune -print0)
done

echo "== 3. App icon catalog =="
# As in Xcode's app target, actool --app-icon puts the icon into the app's own Assets.car and
# Info.plist. Search the app target (Sources/<App>) first, then the top of the project (4 levels:
# ./AppIcon.icon, ./Resources/Assets.xcassets/AppIcon.appiconset); deeper catalogs belong to
# vendored packages and their test apps. APP_ICON names the set (default AppIcon). actool takes
# the .xcassets dir for an appiconset, and the Icon Composer .icon dir itself. Alternate icons
# (ALTERNATE_APP_ICONS / INCLUDE_ALL_APP_ICONS from xtool.env, Xcode 27's
# ASSETCATALOG_COMPILER_ALTERNATE_APPICON_NAMES / _INCLUDE_ALL_APPICON_ASSETS) add the
# --alternate-app-icon / --include-all-app-icons flags and every icon-bearing catalog of the
# target to the same invocation, like Xcode compiles all of a target's catalogs in one call.
icon=${APP_ICON:-AppIcon}
alt_args=()
alt_names=${ALTERNATE_APP_ICONS:-}
if [ -n "$alt_names" ]; then
  for n in $alt_names; do alt_args+=(--alternate-app-icon "$n"); done
fi
if [ "${INCLUDE_ALL_APP_ICONS:-}" = "YES" ]; then
  alt_args+=(--include-all-app-icons)
fi
case "${STANDALONE_ICON_BEHAVIOR:-}" in
  all|none) alt_args+=(--standalone-icon-behavior "$STANDALONE_ICON_BEHAVIOR") ;;
esac
catalogs=()
for src in "Sources/$(basename "$app" .app)" .; do
  [ -d "$src" ] || continue
  depth=; [ "$src" = . ] && depth="-maxdepth 4"
  # shellcheck disable=SC2086
  mapfile -t found < <(find -L "$src" $depth \( -name .build -o -name xtool \) -prune -o \
    \( -name "*.appiconset" -type d -o -name "*.icon" -type d \) -print)
  for f in "${found[@]}"; do
    # Every icon-bearing catalog and .icon of the target joins the call, as Xcode passes all
    # of a target's catalogs; actool selects by --app-icon / --alternate-app-icon /
    # --include-all-app-icons and drops the rest silently, like Apple's.
    case "$f" in
      *.appiconset) catalogs+=("$(dirname "$f")") ;;
      *.icon) catalogs+=("$f") ;;
    esac
  done
  [ "${#catalogs[@]}" = 0 ] || break
done
# Icon Composer icons the generator links into the project root (the primary and its alternates).
for f in ./*.icon; do [ -d "$f" ] && catalogs+=("$f"); done
mapfile -t catalogs < <(for c in "${catalogs[@]}"; do readlink -f "$c"; done | sort -u)
min=$("$PY" -c 'import plistlib,sys; print(plistlib.load(open(sys.argv[1],"rb"))["MinimumOSVersion"])' "$app/Info.plist")
case "${#catalogs[@]}" in
  0) echo "no $icon.appiconset or $icon.icon in the project; App Store upload needs an app icon" ;;
  *)
    "$ACTOOL" "${catalogs[@]}" --compile "$app" --platform iphoneos --app-icon "$icon" \
      "${alt_args[@]}" \
      --minimum-deployment-target "$min" --output-partial-info-plist "$stage/icon.plist" \
      --output-format human-readable-text
    "$PY" -c 'import plistlib,sys; p=sys.argv[1]; d=plistlib.load(open(p,"rb")); d.update(plistlib.load(open(sys.argv[2],"rb")))
plistlib.dump(d, open(p,"wb"), fmt=plistlib.FMT_BINARY)' "$app/Info.plist" "$stage/icon.plist"
    ;;
esac
for appex in "$app"/PlugIns/*.appex; do
  [ -d "$appex" ] || continue
  exname=$(basename "$appex" .appex)
  exicon=""
  while IFS= read -r pair; do
    case "$pair" in "$exname="*) exicon=${pair#*=} ;; esac
  done <<< "${EXTENSION_APP_ICONS:-}"
  [ -n "$exicon" ] || continue
  exsets=()
  while IFS= read -r -d '' f; do exsets+=("$(dirname "$f")"); done \
    < <(find -L "Sources/$exname" -name "$exicon.appiconset" -type d -print0 2>/dev/null)
  [ "${#exsets[@]}" -gt 0 ] || continue
  # An empty placeholder set (the widget's) compiles to nothing in Xcode;
  # skip it instead of emitting an empty icon plist.
  if ! grep -q '"filename"' "${exsets[0]}/$exicon.appiconset/Contents.json"; then
    echo "  $exname: $exicon.appiconset is an empty placeholder; nothing to compile"
    continue
  fi
  "$ACTOOL" "${exsets[0]}" --compile "$appex" --platform iphoneos --app-icon "$exicon" \
    --minimum-deployment-target "$min" --output-partial-info-plist "$stage/$exname-icon.plist" \
    --output-format human-readable-text
  "$PY" -c 'import plistlib,sys; p=sys.argv[1]; d=plistlib.load(open(p,"rb")); d.update(plistlib.load(open(sys.argv[2],"rb")))
plistlib.dump(d, open(p,"wb"), fmt=plistlib.FMT_BINARY)' "$appex/Info.plist" "$stage/$exname-icon.plist"
done

if [ "$device" = 1 ]; then
  echo "== 4. Root-level resources =="
  # Xcode copies every resource of a target to the root of its bundle except
  # what it processes separately: asset catalogs become the root Assets.car
  # (step 3) and the target's Info.plist is merged into the built one. SwiftPM
  # leaves the rest in the resource bundle, where only Bundle.module finds it;
  # code reading Bundle.main (themes, RTF, JSON) traps. Copy what is left of
  # each target's resource bundle to its root, the layout of the proven manual
  # device fix; -n keeps what steps 2-3 placed and the built Info.plist.
  # App Store uploads keep the bundle layout: flattening everything into an
  # upload once stalled App Store processing.
  for target in "$app" "$app"/PlugIns/*.appex; do
    [ -d "$target" ] || continue
    name=$(basename "${target%.*}")
    resbundle=$(find "$target" -maxdepth 1 -type d -name "*_$name.bundle" -print -quit)
    [ -n "$resbundle" ] || continue
    cp -an "$resbundle/." "$target/"
  done
  if [ -n "$team" ]; then
    echo "== 5. Team prefix =="
    [[ "$team" =~ ^[A-Z0-9]{10}$ ]] || { echo "team id '$team' is not a bare 10-character team id" >&2; exit 1; }
    "$PY" "$here/tools/fill-team-prefix.py" --team "$team" "$app"
  fi
  echo "== 6. Placeholder check =="
  # The device path skips asc.py validate; run its surviving-placeholder FAIL
  # on the .app the same way.
  "$PY" - "$app" "$here/tools" <<'PYEOF'
import plistlib, sys
from pathlib import Path
sys.path.insert(0, sys.argv[2])
from asc import placeholder_hits
app = Path(sys.argv[1])
bad = []
for p in sorted(app.rglob("Info.plist")):
    for w in placeholder_hits(plistlib.load(p.open("rb"))):
        bad.append(f"{p.relative_to(app)}:{w or '/'}")
if bad:
    sys.exit("unresolved $(...) placeholders: " + ", ".join(bad))
print(f"no unresolved $(...) placeholders in {app}")
PYEOF
  echo "device app ready: $app"
  echo "install with: xtool install $PWD/$app"
  exit 0
fi

echo "== 4. App Store Info.plist keys and frameworks =="
"$PY" "$ASC" stamp "$app" "${BUILD_NUMBER:-$(date -u +%Y%m%d%H%M)}"
"$PY" "$ASC" frameworks "$app"

echo "== 5. App Intents metadata =="
# Xcode's ExtractAppIntentsMetadata and AppIntentsSSUTraining, for the app and each extension:
# the target's .swiftconstvalues (swift-build emits them) become <bundle>/Metadata.appintents/.
# The tool skips a bundle that does not load AppIntents.framework and exits nonzero on anything it
# cannot reproduce exactly. App Shortcuts training needs Xcode's SiriSSUKitModel resources, which
# install-toolchain.sh keeps next to the SDK cache (or set SSU_RESOURCES).
ssu=${SSU_RESOURCES:-$(ls -dt "$HOME"/.cache/xtool/darwin-*.xtoolsdk.SiriSSUKitModel 2>/dev/null | head -n1 || true)}
sdk_root="$darwin_sdk/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk"
for bundle in "$app" "$app"/PlugIns/*.appex; do
  [ -d "$bundle" ] || continue
  # exe = the product (build dir name); module = its C99 identifier, as Xcode's PRODUCT_MODULE_NAME.
  IFS=$'\t' read -r exe module bid xcbuild < <("$PY" -c 'import plistlib,re,sys; d=plistlib.load(open(sys.argv[1],"rb"))
e = d["CFBundleExecutable"]; m = re.sub(r"\W", "_", e, flags=re.A); m = "_" + m if m[0].isdigit() else m
print(e, m, d["CFBundleIdentifier"], d.get("DTXcodeBuild", ""), sep="\t")' "$bundle/Info.plist")
  mapfile -t constvals < <(find .build/out/Intermediates.noindex \
    -path "*/Release-iphoneos/$exe-t.build/Objects-normal/arm64/*.swiftconstvalues" 2>/dev/null | sort)
  cv_args=()
  [ "${#constvals[@]}" = 0 ] || cv_args=(--const-values "${constvals[@]}")
  "$PY" "$here/tools/appintentsmeta.py" --module-name "$module" --bundle-identifier "$bid" \
    --output "$bundle" --binary-file "$bundle/$exe" --sdk-root "$sdk_root" \
    --xcode-version "${xcbuild:-27A266a}" --timestamp "${SOURCE_DATE_EPOCH:-$(date +%s)}" \
    ${ssu:+--ssu-resources "$ssu"} "${cv_args[@]}"
done

echo "== 6. Distribution identity and signature =="
sign_dir=xtool/ship-signing
if [ -n "${ASC_KEY_ID:-}" ]; then
  "$PY" "$ASC" identity "$app" "$sign_dir"
else
  "$PY" "$ASC" test-identity "$app" "$sign_dir"
fi
team=$("$PY" -c 'import plistlib,sys; print(plistlib.load(open(sys.argv[1],"rb"))["com.apple.developer.team-identifier"])' \
  "$sign_dir/entitlements.plist")
# rcodesign --team-name wants the bare 10-character team id; a certificate common name makes the
# signed app fail to exec on a device (EBADEXEC, Code=85). Stop here if the value is anything else.
[[ "$team" =~ ^[A-Z0-9]{10}$ ]] || { echo "team id '$team' is not a bare 10-character team id" >&2; exit 1; }
# $(AppIdentifierPrefix)/$(TeamIdentifierPrefix) stay placeholders until the
# team is known; fill them before signing seals the Info.plists.
"$PY" "$here/tools/fill-team-prefix.py" --team "$team" "$app"
# Inside-out: every framework, then each PlugIns/*.appex with its own entitlements, is signed
# BEFORE the app, so the app's _CodeSignature seals already-signed nested code. rcodesign's app
# sign preserves the pre-signed nested signatures; the bare --entitlements-xml-file applies to
# the main entity only (verified empirically).
sign_args=(--pem-file "$sign_dir/key.pem" --certificate-der-file "$sign_dir/cert.der" --team-name "$team")
shopt -s nullglob
for framework in "$app"/Frameworks/*.framework; do
  rcodesign sign "${sign_args[@]}" "$framework"
done
for appex in "$app"/PlugIns/*.appex; do
  stem=$(basename "$appex" .appex)
  rcodesign sign "${sign_args[@]}" --entitlements-xml-file "$sign_dir/$stem-entitlements.plist" "$appex"
done
shopt -u nullglob
rcodesign sign "${sign_args[@]}" --entitlements-xml-file "$sign_dir/entitlements.plist" "$app"

echo "== 7. Package =="
name=$(basename "$app" .app)
ipa="$PWD/xtool/$name.ipa"
mkdir "$stage/Payload"
cp -a "$app" "$stage/Payload/"
rm -f "$ipa"
(cd "$stage" && zip -qry "$ipa" Payload)
echo "wrote $ipa"

echo "== 8. Offline App Store validation =="
"$PY" "$ASC" validate "$ipa"

if [ "$upload" = 1 ]; then
  echo "== 9. Upload to App Store Connect =="
  "$PY" "$ASC" upload "$ipa"
fi
